export {default as Login} from './Login';
export { default as Dashboard } from './Dashboard';
export { default as Admin } from './Admin';
export { default as Editor } from './Editor';
export { default as Users } from './Users';
export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from './Calendar';
export { default as FoodPosts } from './FoodPosts';
export { default as Chat } from './Chat';
export {default as UserFeedback} from './UserFeedback';